DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS In_Family;
DROP TABLE IF EXISTS Family;
DROP TABLE IF EXISTS Recipe;
DROP TABLE IF EXISTS Has_Recipe;
DROP TABLE IF EXISTS Grocery_List;
DROP TABLE IF EXISTS On_List;

CREATE TABLE User (
    Email VARCHAR(40) PRIMARY KEY,
    Name VARCHAR(30), 
    Password VARCHAR(20)
);

CREATE TABLE Family (
    FID INT PRIMARY KEY,
    Name VARCHAR(30)
);

CREATE TABLE In_Family (
    email VARCHAR(40),
    FID INT, 
    Own Boolean,
    FOREIGN KEY (Email) REFERENCES User(Email) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (FID) REFERENCES Family(FID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Recipe (
    RID INT PRIMARY KEY,
    Recipe VARCHAR(500),
    Title Varchar(20)
);

CREATE TABLE Has_Recipe (
    RID INT,
    FID INT,
    FOREIGN KEY (RID) REFERENCES Recipe(RID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (FID) REFERENCES Family(FID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Grocery_List (
    LID INT, 
    FID INT,
    name VARCHAR(20),
    FOREIGN KEY (FID) REFERENCES Family(FID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE On_List (
    LID INT, 
    item VARCHAR(30),
    FOREIGN KEY (LID) REFERENCES Grocery_List(LID) ON DELETE CASCADE ON UPDATE CASCADE
)





